# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cat', '0002_auto_20160920_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('dt_modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('status', models.CharField(choices=[('naoavaliado', 'Não avaliado'), ('aprovado', 'Aprovado'), ('recuperacao', 'Recuperação'), ('reprovado', 'Reprovado')], default='naoavaliado', max_length=15)),
                ('nota', models.DecimalField(decimal_places=2, default=0.0, help_text='Informe a nota da prova.', max_digits=2, verbose_name='Nota da prova')),
                ('prova', models.FileField(help_text='Envie a prova.', upload_to='avaliacoes/provas', verbose_name='Arquivo da prova')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('dt_modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='cat.Pessoa')),
            ],
            options={
                'ordering': ['treinamento', 'pessoa'],
            },
        ),
        migrations.CreateModel(
            name='Prazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('dt_modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nome', models.CharField(max_length=15, unique=True)),
                ('qtd_dia', models.IntegerField(verbose_name='Quantidade de dias')),
                ('dia_util', models.BooleanField(default=False, help_text='Contabilizar apenas os dias úteis', verbose_name='Dia útil')),
                ('qtd_prova', models.PositiveIntegerField(default=2, verbose_name='Quantidade de provas')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('dt_modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('titulo', models.CharField(help_text='Deve ter até 50 caracteres.', max_length=50, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('inicial', 'Inicial'), ('rotina', 'Rotina')], max_length=25)),
                ('status', models.CharField(choices=[('AT', 'Ativo'), ('IN', 'Inativo')], default='AT', max_length=2)),
                ('prazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctr.Prazo')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.AddField(
            model_name='matricula',
            name='treinamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinamentos', to='ctr.Treinamento'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='ctr.Matricula'),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together=set([('treinamento', 'pessoa')]),
        ),
    ]
