# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamento',
            name='status',
            field=models.CharField(choices=[('AT', 'Ativo'), ('IN', 'Inativo')], default='IN', max_length=2),
        ),
    ]
