# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cag', '0002_auto_20160917_1520'),
        ('ctr', '0002_auto_20160920_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='treinamento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_tre', to='cag.Empresa'),
        ),
    ]
