# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctr', '0004_auto_20160920_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamento',
            name='status',
            field=models.CharField(choices=[('EM', 'Em Andamento'), ('CA', 'Cancelado'), ('CO', 'Concluído')], default='EM', max_length=2),
        ),
    ]
