# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctr', '0005_auto_20160920_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='status',
            field=models.CharField(choices=[('naoavaliado', 'Não avaliado'), ('aprovado', 'Aprovado'), ('recuperacao', 'Recuperação'), ('reprovado', 'Reprovado')], default='naoavaliado', max_length=15),
        ),
    ]
