# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('dt_modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('situacao', models.CharField(choices=[('AT', 'Ativo'), ('IN', 'Inativo')], default='AT', max_length=2, verbose_name='Situação')),
                ('is_credenciado', models.BooleanField(default=False, verbose_name='É credenciado?')),
            ],
            options={
                'verbose_name_plural': 'Agências',
                'ordering': ['nome'],
                'verbose_name': 'Agência',
            },
        ),
        migrations.CreateModel(
            name='BaseRegional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('dt_modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nome', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Bases Regionais',
                'ordering': ['nome'],
                'verbose_name': 'Base Regional',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('dt_modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/empresas')),
            ],
            options={
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='HorarioFuncionamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('dt_modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('entrada1', models.TimeField(verbose_name='Entrada 1')),
                ('saida1', models.TimeField(verbose_name='Saída 1')),
                ('entrada2', models.TimeField(blank=True, null=True, verbose_name='Entrada 2')),
                ('saida2', models.TimeField(blank=True, null=True, verbose_name='Saída 2')),
            ],
            options={
                'verbose_name_plural': 'Horários de funcionamento',
                'verbose_name': 'Horário de funcionamento',
            },
        ),
        migrations.CreateModel(
            name='PontoAtendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('dt_modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nome', models.CharField(max_length=10, unique=True)),
                ('qtd', models.PositiveIntegerField(verbose_name='Qtd de pontos')),
            ],
            options={
                'verbose_name_plural': 'PAs - Pontos de Atendimentos',
                'ordering': ['nome'],
                'verbose_name': 'PA - Ponto de Atendimento',
            },
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('dt_modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nome', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Regionais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoAgenciaPex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('dt_modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nome', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos PEX',
                'verbose_name': 'Tipo PEX',
            },
        ),
        migrations.CreateModel(
            name='TipoEstabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('dt_modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nome', models.CharField(max_length=35, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Estabelecimentos',
                'verbose_name': 'Tipo de Estabelecimento',
            },
        ),
        migrations.CreateModel(
            name='TipoLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('dt_modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Link',
                'ordering': ['nome'],
                'verbose_name': 'Tipo de Link',
            },
        ),
        migrations.CreateModel(
            name='DetalheAgencia',
            fields=[
                ('dt_criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('dt_modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=8, null=True, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Município')),
                ('uf', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Brasília'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('tel_residencial', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone residencial')),
                ('tel_celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('agencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detalhes', serialize=False, to='cag.Agencia')),
                ('uc', models.PositiveIntegerField(blank=True, null=True, verbose_name='Unidade consumidora')),
                ('condicao', models.CharField(choices=[('alugado', 'Alugado'), ('comodato', 'Comodato'), ('proprio', 'Próprio'), ('naoinformado', 'Não informado')], default='alugado', max_length=15, verbose_name='Condição do prédio')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='cag.HorarioFuncionamento')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='cag.TipoLink')),
            ],
            options={
                'verbose_name_plural': 'Detalhes das Agências',
                'verbose_name': 'Detalhe da Agência',
            },
        ),
        migrations.AddField(
            model_name='pontoatendimento',
            name='tipologia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_pex', to='cag.TipoAgenciaPex'),
        ),
        migrations.AddField(
            model_name='agencia',
            name='baseregional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bases', to='cag.BaseRegional', verbose_name='Base regional'),
        ),
        migrations.AddField(
            model_name='agencia',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_ag', to='cag.Empresa'),
        ),
        migrations.AddField(
            model_name='agencia',
            name='regional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regionais', to='cag.Regional'),
        ),
        migrations.AddField(
            model_name='detalheagencia',
            name='pa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pas_ag', to='cag.PontoAtendimento'),
        ),
    ]
