# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160923_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/usuario/perfil'),
        ),
    ]
