# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 03:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='doc_cpf',
            field=models.CharField(help_text='Informe o CPF', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(regex='[0-9]{3}\\.?[0-9]{3}\\.?[0-9]{3}\\-?[0-9]{2}')], verbose_name='CPF'),
        ),
    ]
